### **CHSH Inequality for Maximally Entangled state(Bell State)**

##### **Using convex optimization technique (install the necessary library for SDP- pip install cvxpy)**
- **This will use any general werner state density matrix to maximize the trace also that should be the PSD Matrix**

In [47]:
import cvxpy as cp
import numpy as np

# Define Pauli matrices 
I = np.eye(2)
sigma_x = np.array([[0, 1], [1, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Define the observables A1, A2, B1, B2
A1 = sigma_x
A2 = sigma_z
B1 = (sigma_x + sigma_z) / np.sqrt(2)
B2 = (sigma_x - sigma_z) / np.sqrt(2)

# Define the CHSH operator
CHSH = np.kron(A1, B1) + np.kron(A1, B2) + np.kron(A2, B1) - np.kron(A2, B2)

# Define the Gram matrix G as a variable (4x4 symmetric matrix)
G = cp.Variable((4, 4), symmetric=True)

# Define the constraints: G must be positive semi-definite and have ones on the diagonal
constraints = [G >> 0]  # G is PSD
constraints += [G[i, i] == 1 for i in range(4)]  # Diagonal elements are 1


# Define the objective function: maximize 1/2 * Tr(G CHSH)
objective = cp.Maximize(0.5 * cp.trace(G @ CHSH))

# Define the SDP problem
problem = cp.Problem(objective, constraints)

# Solve the SDP problem
result = problem.solve()

# Output the result
print("Optimal value of the objective function:", result)
print("Optimal Gram matrix G:")
print(G.value)


Optimal value of the objective function: 2.8284271252760966
Optimal Gram matrix G:
[[1.00000000e+00 7.91864900e-15 7.29860160e-15 9.99999965e-01]
 [7.91864900e-15 1.00000000e+00 1.00000003e+00 8.72392264e-15]
 [7.29860160e-15 1.00000003e+00 1.00000000e+00 8.10387524e-15]
 [9.99999965e-01 8.72392264e-15 8.10387524e-15 1.00000000e+00]]


##### **Calculate CHSH value without SDP**

In [50]:
import numpy as np

# Define the Bell state |Φ+⟩
phi_plus = (1 / np.sqrt(2)) * np.array([1, 0, 0, 1])  # State vector representation

# Define Pauli matrices 
sigma_x = np.array([[0, 1], [1, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Define the observables A1, A2, B1, B2
A1 = sigma_x
A2 = sigma_z
B1 = (sigma_x + sigma_z) / np.sqrt(2)
B2 = (sigma_x - sigma_z) / np.sqrt(2)

# Function to calculate the expectation value <psi| (A ⊗ B) |psi>
def expectation_value(state, A, B):
    # Calculate the tensor product
    operator = np.kron(A, B)
    return np.real(np.dot(state.conj().T, np.dot(operator, state)))

# Calculate expectation values for each combination
E_A1_B1 = expectation_value(phi_plus, A1, B1)
E_A1_B2 = expectation_value(phi_plus, A1, B2)
E_A2_B1 = expectation_value(phi_plus, A2, B1)
E_A2_B2 = expectation_value(phi_plus, A2, B2)

# Calculate the CHSH value
CHSH_value = E_A1_B1 + E_A1_B2 + E_A2_B1 - E_A2_B2
print("CHSH value for Bell state:", CHSH_value)

CHSH value for Bell state: 2.8284271247461894


### Any werner state density matrix correlated to bell state have CHSH value < 2*root2

# General Werner State

The Werner state is a type of mixed quantum state defined in the context of bipartite quantum systems. It is particularly significant in quantum information theory as it explores the boundaries between entangled and separable states.

## Definition

For a bipartite quantum system with two qubits, the general Werner state \( \rho_W \) can be expressed as:

\[
\rho_W = p \cdot |\Psi^-\rangle \langle \Psi^-| + (1 - p) \cdot \frac{I}{4}
\]

where:
- \( |\Psi^-\rangle = \frac{1}{\sqrt{2}} (|01\rangle - |10\rangle) \) is the Bell state.
- \( I \) is the identity matrix of size \( 4 \times 4 \).
- \( p \) is a parameter that ranges from \( 0 \) to \( 1 \), determining the mixture of the entangled state and the completely mixed state.

## Properties

- **Entanglement**: The Werner state is entangled for \( p > \frac{1}{3} \) and becomes separable for \( p \leq \frac{1}{3} \).
- **CHSH Inequality**: The CHSH inequality can be violated for values of \( p \) corresponding to entangled Werner states.
- **Applications**: Werner states are used to study quantum non-locality, quantum teleportation, and quantum key distribution.

## Example

For \( p = 1 \), the Werner state reduces to the maximally entangled state \( |\Psi^-\rangle \). For \( p = 0 \), it corresponds to the completely mixed state.

### Summary

The general Werner state provides a useful framework for understanding the transition between entangled and separable states in quantum mechanics, serving as a key concept in the study of quantum entanglement and its applications in quantum information science.


In [51]:
import cvxpy as cp
import numpy as np

# Define Pauli matrices 
I = np.eye(2)
sigma_x = np.array([[0, 1], [1, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Define the observables A1, A2, B1, B2
A1 = sigma_x
A2 = sigma_z
B1 = (sigma_x + sigma_z) / np.sqrt(2)
B2 = (sigma_x - sigma_z) / np.sqrt(2)

# Define the CHSH operator
CHSH = np.kron(A1, B1) + np.kron(A1, B2) + np.kron(A2, B1) - np.kron(A2, B2)

# Define the Gram matrix G as a variable (4x4 symmetric matrix)
G = cp.Variable((4, 4), symmetric=True)

# Define the constraints: G must be positive semi-definite and have ones on the diagonal
constraints = [G >> 0]  # G is PSD
constraints += [G[i, i] == 1 for i in range(4)]  # Diagonal elements are 1

# Optionally, add a constraint that G should be related to the Bell state density
# For example, require that the off-diagonal elements reflect the Bell state's correlations
constraints += [G[0, 3] == 1/2]  # Example correlation for |Φ+⟩, adjust as needed

# Define the objective function: maximize 1/2 * Tr(G CHSH)
objective = cp.Maximize(0.5 * cp.trace(G @ CHSH))

# Define the SDP problem
problem = cp.Problem(objective, constraints)

# Solve the SDP problem
result = problem.solve()

# Output the result
print("Optimal value of the objective function:", result)
print("Optimal Gram matrix G:")
print(G.value)


Optimal value of the objective function: 2.121320355338266
Optimal Gram matrix G:
[[ 1.00000000e+00  1.65260510e-16  2.17560738e-16  5.00000000e-01]
 [ 1.65260510e-16  1.00000000e+00  1.00000001e+00 -1.21806228e-14]
 [ 2.17560738e-16  1.00000001e+00  1.00000000e+00 -1.20813856e-14]
 [ 5.00000000e-01 -1.21806228e-14 -1.20813856e-14  1.00000000e+00]]


In [20]:
import numpy as np

# Define Pauli matrices and the identity matrix
I = np.eye(2)
sigma_x = np.array([[0, 1], [1, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Define the Bell state |Φ+⟩
phi_plus_flat = np.array([1, 0, 0, 1]) / np.sqrt(2)

# Define the CHSH operator
def chsh_operator():
    A1 = sigma_x
    A2 = sigma_z
    B1 = (sigma_x + sigma_z) / np.sqrt(2)
    B2 = (sigma_x - sigma_z) / np.sqrt(2)

    CHSH = np.kron(A1, B1) + np.kron(A1, B2) + np.kron(A2, B1) - np.kron(A2, B2)
    return CHSH

# Define the Werner state
def werner_state(p):
    I_4 = np.kron(I, I)
    rho_W = (1 - p) * I_4 / 4 + p * np.outer(phi_plus_flat, phi_plus_flat)
    return rho_W

# Calculate CHSH value for a Werner state
def chsh_value(state, CHSH):
    return np.trace(np.dot(state, CHSH)).real

# Parameters
p = 1
rho_W = werner_state(p)
CHSH = chsh_operator()

# Calculate CHSH value for Werner state
chsh_val = chsh_value(rho_W, CHSH)

# Print results
print("Werner State Density Matrix (p=1):")
print(rho_W)
print("\nCHSH Value for Werner State (p=1):")
print(chsh_val)


Werner State Density Matrix (p=1):
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

CHSH Value for Werner State (p=1):
2.8284271247461894


In [ ]:
import cvxpy as cp
import numpy as np
from qutip import sigmax,sigmaz

# Define Pauli matrices 
I = np.eye(2)
sigma_x = np.array([[0, 1], [1, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Define the observables A1, A2, B1, B2
A1 = sigmax()
A2 = sigmaz()
B1 = (sigmax() + sigmaz()) / np.sqrt(2)
B2 = (sigmax() - sigmaz()) / np.sqrt(2)

# Define the CHSH operator
CHSH = cp.Constant(np.kron(A1, B1) + np.kron(A1, B2) + np.kron(A2, B1) - np.kron(A2, B2))

# Define the Gram matrix G as a variable (4x4 symmetric matrix)
G = cp.Variable((4, 4), symmetric=True)

# Define the constraints: G must be positive semi-definite and have ones on the diagonal
constraints = [G >> 0]  # G is PSD
constraints += [G[i, i] == 1 for i in range(4)]  # Diagonal elements are 1

# Define the objective function: maximize 1/2 * Tr(G CHSH)
objective = cp.Maximize(0.5 * cp.trace(G @ CHSH))

# Define the SDP problem
problem = cp.Problem(objective, constraints)

# Solve the SDP problem
result = problem.solve()

# Output the result
print("Optimal value of the objective function:", result)
print("Optimal Gram matrix G:")
print(G.value)
